<script language="javascript"><!--
$(document).ready(function() {
  $('#page_effect').fadeIn(500);
  $('#datepicker1').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker2').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker3').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker4').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker5').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker6').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker7').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker8').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker9').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker10').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker11').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker12').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker13').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker14').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker15').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker16').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker17').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker18').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker19').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker20').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker21').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker22').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker23').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker24').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker25').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker26').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker27').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker28').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker29').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker30').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker31').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker32').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker33').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker34').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker35').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker36').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker37').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker38').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
  $('#datepicker39').datepicker({ inline: true, dateFormat: 'yy-mm-dd' });
});
--></script>
