#!/usr/bin/expect -f

set force_conservative 0 ;# set to 1 to force

if {$force_conservative} {
  set send_slow {1 .1}
  proc send {ignore arg} {
    sleep .1
    exp_send -s -- $arg
  }
}

set timeout -1
spawn $env(SHELL)
match_max 100000
expect -exact "$ "
send -- "ssh vista@pseudovista.vaftl.us\n"
expect -exact "Password: "
send -- "Innovat3.\r"
expect -exact "ACCESS CODE:"
send -- "cprs1234\r"
expect "VERIFY CODE:"
send -- "cprs4321\$\r"
